/**
 * Command envelope and result vocabulary per RFC-0001 §10.1. Every
 * durable mutation crosses the Project API as one of these; the
 * renderer may import this package, never @ew/persistence.
 */

export interface CommandEnvelope<P = unknown> {
  /** UUIDv7, generated by the issuer. */
  commandId: string
  projectId: string
  commandType: string
  commandVersion: number
  /** §10.2: stale values return a structured conflict. Optional per §10.1. */
  expectedProjectRevision?: number
  /** ISO-8601. */
  issuedAt: string
  payload: P
}

export interface AffectedRecord {
  kind:
    | 'project'
    | 'note'
    | 'node'
    | 'canvas'
    | 'placement'
    | 'asset'
    | 'tag'
    | 'decoration'
    | 'link'
    | 'bookmark'
  id: string
}

/**
 * Inverse command per invariant 24: structural undo emits inverse
 * commands through the same pipeline. Carried on the result for the
 * in-memory undo stack (EPIC-007); never persisted as an event store.
 */
export interface InverseCommand {
  commandType: string
  commandVersion: number
  payload: unknown
}

export interface CommittedResult {
  status: 'committed'
  commandId: string
  revision: number
  affected: AffectedRecord[]
  /** null when the command is not invertible (e.g. purge). */
  inverse: InverseCommand | null
}

export interface ConflictResult {
  status: 'conflict'
  commandId: string
  expectedRevision: number
  actualRevision: number
}

/** Structured domain failure, e.g. NOTE_TITLE_CONFLICT (§7.7). */
export interface ErrorResult {
  status: 'error'
  commandId: string
  code: string
  message: string
  details?: Record<string, unknown>
}

export type CommandResult = CommittedResult | ConflictResult | ErrorResult

/**
 * Thrown by handlers to abort the surrounding transaction and
 * surface a structured ErrorResult.
 */
export class DomainError extends Error {
  constructor(
    readonly code: string,
    message: string,
    readonly details?: Record<string, unknown>,
  ) {
    super(message)
    this.name = 'DomainError'
  }
}

/** Event emitted after every committed command (§11.3 subscribe). */
export interface ProjectChangedEvent {
  type: 'project-changed'
  projectId: string
  revision: number
  commandId: string
  commandType: string
  affected: AffectedRecord[]
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

/** Structural validation only; domain checks belong to handlers. */
export function validateEnvelope(envelope: unknown): string[] {
  const errors: string[] = []
  if (typeof envelope !== 'object' || envelope === null) {
    return ['envelope must be an object']
  }
  const e = envelope as Partial<CommandEnvelope>
  if (typeof e.commandId !== 'string' || !UUID_RE.test(e.commandId)) {
    errors.push('commandId must be a UUID')
  }
  if (typeof e.projectId !== 'string' || e.projectId.length === 0) {
    errors.push('projectId must be a non-empty string')
  }
  if (typeof e.commandType !== 'string' || e.commandType.length === 0) {
    errors.push('commandType must be a non-empty string')
  }
  if (!Number.isInteger(e.commandVersion) || (e.commandVersion as number) < 1) {
    errors.push('commandVersion must be a positive integer')
  }
  if (
    e.expectedProjectRevision !== undefined &&
    (!Number.isInteger(e.expectedProjectRevision) || e.expectedProjectRevision < 0)
  ) {
    errors.push('expectedProjectRevision must be a non-negative integer when present')
  }
  if (typeof e.issuedAt !== 'string' || Number.isNaN(Date.parse(e.issuedAt))) {
    errors.push('issuedAt must be an ISO-8601 timestamp')
  }
  if (!('payload' in e)) {
    errors.push('payload is required')
  }
  return errors
}
